from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Window(object):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.resize(1029, 493)
        self.centralwidget = QtWidgets.QWidget(Window)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1001, 28))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.signal1 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.signal1.setObjectName("signal1")
        self.horizontalLayout.addWidget(self.signal1)
        self.signal2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.signal2.setObjectName("signal2")
        self.horizontalLayout.addWidget(self.signal2)
        self.signal3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.signal3.setObjectName("signal3")
        self.horizontalLayout.addWidget(self.signal3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(10, 60, 1011, 381))
        self.graphicsView.setObjectName("graphicsView")
        Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1029, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        Window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Window)
        self.statusbar.setObjectName("statusbar")
        Window.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(Window)
        self.actionExit.setObjectName("actionExit")
        self.actionSave = QtWidgets.QAction(Window)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(Window)
        QtCore.QMetaObject.connectSlotsByName(Window)
        Window.setTabOrder(self.signal1, self.signal2)
        Window.setTabOrder(self.signal2, self.signal3)
        Window.setTabOrder(self.signal3, self.pushButton_4)

    def retranslateUi(self, Window):
        _translate = QtCore.QCoreApplication.translate
        Window.setWindowTitle(_translate("Window", "Signals Magic"))
        self.pushButton.setText(_translate("Window", "Start/Stop"))
        self.signal1.setToolTip(_translate("Window", "Generates a 1hz sine wave"))
        self.signal1.setText(_translate("Window", "1Hz Signal"))
        self.signal2.setToolTip(_translate("Window", "Generates a 2hz sine wave"))
        self.signal2.setText(_translate("Window", "2Hz Signal"))
        self.signal3.setToolTip(_translate("Window", "Generates a 3hz sine wave"))
        self.signal3.setText(_translate("Window", "3Hz Signal"))
        self.pushButton_4.setText(_translate("Window", "Exit"))
        self.menuFile.setTitle(_translate("Window", "File"))
        self.actionExit.setText(_translate("Window", "Exit"))
        self.actionExit.setToolTip(_translate("Window", "Close the application"))
        self.actionExit.setShortcut(_translate("Window", "Ctrl+Q"))
        self.actionSave.setText(_translate("Window", "Save"))
        self.actionSave.setShortcut(_translate("Window", "Ctrl+S"))

